version: '3.8'

services:
  computer-use-demo:
    build: 
      context: .
      dockerfile: Dockerfile
    image: computer-use-demo:local
    env_file: .env
    ports:
      - "5900:5900"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
    volumes:
      - ./computer_use_demo:/home/computeruse/computer_use_demo/
      - ${HOME}/.anthropic:/home/computeruse/.anthropic
    tty: true
    stdin_open: true
